# Generated by Django 2.0.5 on 2018-05-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treeline_gg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesanalyzed',
            name='game_length',
            field=models.IntegerField(),
        ),
    ]
