# Generated by Django 2.0.5 on 2018-05-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treeline_gg', '0002_auto_20180528_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesanalyzed',
            name='starting_items',
            field=models.CharField(default='', max_length=50),
        ),
    ]
