# Generated by Django 2.0.5 on 2018-05-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treeline_gg', '0004_auto_20180529_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesanalyzed',
            name='game_rank',
            field=models.CharField(default='', max_length=20),
        ),
    ]
