# Generated by Django 2.0.5 on 2018-06-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treeline_gg', '0005_gamesanalyzed_game_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesanalyzed',
            name='skilling_order',
            field=models.CharField(default='', max_length=35),
        ),
    ]
