# Generated by Django 2.0.5 on 2018-06-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treeline_gg', '0006_gamesanalyzed_skilling_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestpractices',
            old_name='finalItems',
            new_name='final_items',
        ),
        migrations.RenameField(
            model_name='bestpractices',
            old_name='role_1',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='bestpractices',
            old_name='role_2',
            new_name='role_type',
        ),
        migrations.RenameField(
            model_name='bestpractices',
            old_name='skillingOrder',
            new_name='skilling_order',
        ),
        migrations.RenameField(
            model_name='bestpractices',
            old_name='startingItems',
            new_name='starting_items',
        ),
        migrations.AddField(
            model_name='bestpractices',
            name='playrate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestpractices',
            name='winrate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
