# Generated by Django 2.0.5 on 2018-06-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treeline_gg', '0007_auto_20180611_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestpractices',
            name='champ_profile',
        ),
        migrations.AlterField(
            model_name='bestpractices',
            name='playrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bestpractices',
            name='winrate',
            field=models.FloatField(default=0),
        ),
    ]
