# Generated by Django 2.0.5 on 2018-06-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treeline_gg', '0009_auto_20180611_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestpractices',
            name='event_id',
        ),
        migrations.AddField(
            model_name='bestpractices',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
