# Generated by Django 2.0.5 on 2018-06-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treeline_gg', '0011_auto_20180611_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpractices',
            name='games_plaed',
            field=models.IntegerField(default=0),
        ),
    ]
